import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube

} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react';


const style = {
  imgCircle: 'relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden',
  imgfit: 'object-cover',
}
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Tabatha Moreno</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 

      <main className='bg-white px-10 md:px-20 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>DevelopedbyTab</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl' /> </li>
              <li className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'><a hrfe='#' />Resume</li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Tabatha Moreno</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Software Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>Text dummy
            Text dummy
            Text dummy
            Text dummyText dummyText dummyText dummyText dummyText dummyText dummyText dummyText dummyText dummy</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className={style.imgCircle}>
            <Image src={deved} fill className={style.imgfit} />
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
            <p className='text-md py-2 leading-8 text-gray-800'>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
          </div>

          <div className='md:flex gap-10 lg:flex'>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <Image className='inline' src={design} width={100} height={100}/>
            <h3 className='text-lg font-medium pt-8 pb-2 '>Beauiful Design</h3>
            <p className='py-2'>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
            <h4 className='py-4 text-teal-600'>Tools I use</h4>
            <p className='text-gray-800 py-1'>photoshop</p>
            <p className='text-gray-800 py-1'>Figma</p>
            <p className='text-gray-800 py-1'>Canva</p>
          </div>

          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <Image className='inline' src={code} width={100} height={100}/>
            <h3 className='text-lg font-medium pt-8 pb-2 '>Beauiful Design</h3>
            <p className='py-2'>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
            <h4 className='py-4 text-teal-600'>Tools I use</h4>
            <p className='text-gray-800 py-1'>photoshop</p>
            <p className='text-gray-800 py-1'>Figma</p>
            <p className='text-gray-800 py-1'>Canva</p>
          </div>

          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <Image className='inline' src={consulting} width={100} height={100}/>
            <h3 className='text-lg font-medium pt-8 pb-2 '>Beauiful Design</h3>
            <p className='py-2'>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
            <h4 className='py-4 text-teal-600'>Tools I use</h4>
            <p className='text-gray-800 py-1'>photoshop</p>
            <p className='text-gray-800 py-1'>Figma</p>
            <p className='text-gray-800 py-1'>Canva</p>
          </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'>portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
            <p className='text-md py-2 leading-8 text-gray-800'>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className="rounded-lg object-cover w-100"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className="rounded-lg object-cover"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className="rounded-lg object-cover"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className="rounded-lg object-cover"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className="rounded-lg object-cover"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className="rounded-lg object-cover"/>
            </div>
          </div>
        </section>
      </main>

    </div>
  )
}
